### ISSUE TITLE
How use condo with private docker registry?

### ISSUE THREAD

**Issue by khmelevskii** [prepor/condo#26]
I see that https://github.com/prepor/condo/blob/b9a16829e6ffef10df2fefdadf143b56d33f0b97/src/condo_docker.ml#L22 but don't understand

**Comment by khmelevskii** [comment]
and  use X-Registry-Auth
https://github.com/prepor/condo/blob/b9a16829e6ffef10df2fefdadf143b56d33f0b97/src/condo_docker.ml#L116

**Comment by khmelevskii** [comment]
got it
```
docker run -v $HOME/condo-specs:/var/lib/condo -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.docker/config.json:/home/root/.docker/config.json -ti prepor/condo:v0.10.2 --docker-config=/home/root/.docker/config.json
```

**Comment by prepor** [comment]
Great, I'm sorry for delay with answer :)
